//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homeinventory22.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("homeinventory22.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13_Sun_Creams_That_Work_On_All_Skin_Tones___No_Chalky_Residue_In_Sight {
            get {
                object obj = ResourceManager.GetObject("13 Sun Creams That Work On All Skin Tones - No Chalky Residue In Sight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_Golden_Rules_For_Living_The_Laptop_Lifestyle {
            get {
                object obj = ResourceManager.GetObject("4 Golden Rules For Living The Laptop Lifestyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_Best_Moisturizing_Products_for_Dry_Hair {
            get {
                object obj = ResourceManager.GetObject("5 Best Moisturizing Products for Dry Hair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5d4c178b_7850_4c10_adc1_703c3d9f20de {
            get {
                object obj = ResourceManager.GetObject("5d4c178b-7850-4c10-adc1-703c3d9f20de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9_Best_35mm_Film_Cameras_for_Beginners__Available_in_2021__ {
            get {
                object obj = ResourceManager.GetObject("9 Best 35mm Film Cameras for Beginners (Available in 2021!)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Air_Fryer_Potato_Chips {
            get {
                object obj = ResourceManager.GetObject("Air Fryer Potato Chips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Apple_AirPods_In_Ear_Wireless_Headphones_with_Standard_Charging_Case__Gen_2____White__MV7N2AM_A_ {
            get {
                object obj = ResourceManager.GetObject("Apple AirPods In-Ear Wireless Headphones with Standard Charging Case (Gen 2) - Wh" +
                        "ite (MV7N2AM-A)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aubergines {
            get {
                object obj = ResourceManager.GetObject("aubergines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_Icon_Profile_Icon_Member_Login_Vector_Isolated__Login_Icons__Profile_Icons__Avatar_Icons_PNG_and_Vector_with_Transparent_Background_for_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Avatar Icon Profile Icon Member Login Vector Isolated, Login Icons, Profile Icons" +
                        ", Avatar Icons PNG and Vector with Transparent Background for Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Baby_Dove_Lotion_Rich {
            get {
                object obj = ResourceManager.GetObject("Baby Dove Lotion Rich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Beautiful_Make_able_Recipes___The_Modern_Proper {
            get {
                object obj = ResourceManager.GetObject("Beautiful Make-able Recipes _ The Modern Proper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bose_SoundLink_Flex {
            get {
                object obj = ResourceManager.GetObject("Bose SoundLink Flex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carrots_ {
            get {
                object obj = ResourceManager.GetObject("Carrots_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chocolate_Espresso_Snickerdoodles__1_ {
            get {
                object obj = ResourceManager.GetObject("Chocolate Espresso Snickerdoodles (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cooking_Icons {
            get {
                object obj = ResourceManager.GetObject("Cooking Icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Creamy_Mixed_Mushroom_and_Brie_Soup {
            get {
                object obj = ResourceManager.GetObject("Creamy Mixed Mushroom and Brie Soup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Danish_Ballhead_Cabbage_Seeds___Cabbage_Ukrainian_Autumn_Seeds___Heirloom____Vegetable_Seeds___NON_GMO__1_ {
            get {
                object obj = ResourceManager.GetObject("Danish Ballhead Cabbage Seeds - Cabbage Ukrainian Autumn Seeds - Heirloom -  Vege" +
                        "table Seeds - NON GMO (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dove_For_Women_Original_Anti_Perspirant_Cream_Stick_40Ml {
            get {
                object obj = ResourceManager.GetObject("Dove For Women Original Anti-Perspirant Cream Stick 40Ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__3_ {
            get {
                object obj = ResourceManager.GetObject("download (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_Assortment_Of_Nuts_In_Ceramic_Plates__Cashew__Hazelnuts__Walnuts__Pistachio__Pecans__Pine_Nuts__Peanut__Raisins {
            get {
                object obj = ResourceManager.GetObject("Download Assortment Of Nuts In Ceramic Plates_ Cashew, Hazelnuts, Walnuts, Pistac" +
                        "hio, Pecans, Pine Nuts, Peanut, Raisins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_image_of_Corn_on_the_cob_on_a_rigid_surface_by_Monika_about_corn__corn_cob__food_healthy_white_background_herbs__kitchen_background__and_aerial_1225252 {
            get {
                object obj = ResourceManager.GetObject("Download premium image of Corn on the cob on a rigid surface by Monika about corn" +
                        ", corn cob, food healthy white background herbs, kitchen background, and aerial " +
                        "1225252", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dr__Gundry_s_Savory_and_Satisfying_Broccoli_Cheddar_Quiche {
            get {
                object obj = ResourceManager.GetObject("Dr_ Gundry\'s Savory and Satisfying Broccoli Cheddar Quiche", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flat_Lay_Bowls_With_Dried_Fruits {
            get {
                object obj = ResourceManager.GetObject("Flat Lay Bowls With Dried Fruits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fresh_lettuce_leaves {
            get {
                object obj = ResourceManager.GetObject("fresh lettuce leaves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Garlic_Bulbs_by_Susan_Findlay {
            get {
                object obj = ResourceManager.GetObject("Garlic Bulbs by Susan Findlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Greens {
            get {
                object obj = ResourceManager.GetObject("Greens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Haden_Silt_Green_Dorchester_Microwave___Reviews___Crate_and_Barrel {
            get {
                object obj = ResourceManager.GetObject("Haden Silt Green Dorchester Microwave + Reviews _ Crate and Barrel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hand_Soap__Sanitizer___PocketBac {
            get {
                object obj = ResourceManager.GetObject("Hand Soap, Sanitizer & PocketBac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HOMEMADE_CRACKERS_AND_SUPER_BOWL_SNACK_IDEAS {
            get {
                object obj = ResourceManager.GetObject("HOMEMADE CRACKERS AND SUPER BOWL SNACK IDEAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Homemade_Soft_Pretzels_with_Three_Cheese_Dip {
            get {
                object obj = ResourceManager.GetObject("Homemade Soft Pretzels with Three Cheese Dip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap How_to_Make_Stovetop_Popcorn {
            get {
                object obj = ResourceManager.GetObject("How to Make Stovetop Popcorn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap How_to_Roast_Beets___Vanilla_And_Bean {
            get {
                object obj = ResourceManager.GetObject("How to Roast Beets _ Vanilla And Bean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap How_to_Roast_Beets___Vanilla_And_Bean1 {
            get {
                object obj = ResourceManager.GetObject("How to Roast Beets _ Vanilla And Bean1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_pink_icon {
            get {
                object obj = ResourceManager.GetObject("Light pink icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Listerine_Cool_Mint_Mouth_Wash___250ml {
            get {
                object obj = ResourceManager.GetObject("Listerine Cool Mint Mouth Wash - 250ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mini_Lighted_Digital_Car_Clock_Auto_Car_Truck_Dashboard_Date_Time_Calendar_Black_Vehicle_Electronic_Digital_Clock {
            get {
                object obj = ResourceManager.GetObject("Mini Lighted Digital Car Clock Auto Car Truck Dashboard Date Time Calendar Black " +
                        "Vehicle Electronic Digital Clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NEWYES_10Inch_Bluetooth_Archive_Synchronize_Writing_Tablet_save_Drawing_LCD_Office_Family_Graffiti_Toy_Gift {
            get {
                object obj = ResourceManager.GetObject("NEWYES 10Inch Bluetooth Archive Synchronize Writing Tablet save Drawing LCD Offic" +
                        "e Family Graffiti Toy Gift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NuMex_Joe_E__Parker_Chili_Peppers {
            get {
                object obj = ResourceManager.GetObject("NuMex Joe E_ Parker Chili Peppers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pastel_Purple___Lilac___Lavender___Solid_Color_Throw_Pillow_by_MultiFascinated {
            get {
                object obj = ResourceManager.GetObject("Pastel Purple - Lilac - Lavender - Solid Color Throw Pillow by MultiFascinated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PEA_SOUP {
            get {
                object obj = ResourceManager.GetObject("PEA SOUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Peach_Hearts_Premium_Candy {
            get {
                object obj = ResourceManager.GetObject("Peach Hearts Premium Candy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Premium_Photo___Empty_shopping_cart_on_pink_background__shopping__shopping_online_concept {
            get {
                object obj = ResourceManager.GetObject("Premium Photo _ Empty shopping cart on pink background_ shopping, shopping online" +
                        " concept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Premium_Vector___Soap_with_froth_bubble___icon_illustration__healthcare_and_medical_icon_concept_white_isolated__1_ {
            get {
                object obj = ResourceManager.GetObject("Premium Vector _ Soap with froth bubble   icon illustration_ healthcare and medic" +
                        "al icon concept white isolated (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profile {
            get {
                object obj = ResourceManager.GetObject("profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_Onion_With_Cut_In_Half_Isolated_On_White_Background__Stock_Image___Image_of_background__plant__105173215 {
            get {
                object obj = ResourceManager.GetObject("Red Onion With Cut In Half Isolated On White Background_ Stock Image - Image of b" +
                        "ackground, plant_ 105173215", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Samsung_32__720p_HD_M4500B_Series_4_Smart_Television___UN32M4500BFXZC {
            get {
                object obj = ResourceManager.GetObject("Samsung 32_ 720p HD M4500B Series 4 Smart Television - UN32M4500BFXZC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_13_Whitening_Toothpastes_Dentists_Actually_Recommend {
            get {
                object obj = ResourceManager.GetObject("The 13 Whitening Toothpastes Dentists Actually Recommend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap These_Are_Healthiest_Vegetables_You_Can_Eat__According_to_a_Nutritionist {
            get {
                object obj = ResourceManager.GetObject("These Are Healthiest Vegetables You Can Eat, According to a Nutritionist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tonymoly___Antibacteria_Cotton_Swabs__300pcs_ {
            get {
                object obj = ResourceManager.GetObject("Tonymoly - Antibacteria Cotton Swabs (300pcs)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
